version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1 # will be used to interact with AWS services
  eb: circleci/aws-elastic-beanstalk@1.0.0 # will be used to push the API to AWS EB
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install # installs node to the image
      - checkout
      - aws-cli/setup # setups the AWS CLI with the credentials added in CircleCi
      - eb/setup # setups the EB CLI
      
      - run: # sends the env variables stored in the circleci project to AWS EB
          name: "Send ENV variables to AWS EB"
          command: cd udagram-api && eb setenv DB_PORT=${MY_ENV_VAR} JWT_SECRET=${JWT_SECRET} PORT=${PORT} POSTGRES_HOST=${POSTGRES_HOST} POSTGRES_PASSWORD=${POSTGRES_PASSWORD} POSTGRES_USERNAME=${POSTGRES_USERNAME} URL=${URL}
      
      - run: # installs the frontend dependencies
          name: Front-End Install
          command: |
            npm run frontend:install
      
      - run: # installs the backend dependencies
          name: Back-End Install
          command: |
            npm run backend:install
      
      - run: # builds the frontend app
          name: Front-End Build
          command: |
            npm run frontend:build
      
      - run: # builds the backend API
          name: Back-End Build
          command: |
            npm run backend:build

      - run: # tests the frontend
          name: Test Frontend
          command: |
            npm run frontend:test

      - run: # test the backend
          name: Test Backend
          command: |
            npm run backend:test

      - run: # deploys the frontend by uploading the app files to AWS S3
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      
      - run: # deploys the backend API by uploading the files to AWS EB
          name: Deploy Backend
          command: |
            npm run backend:deploy

workflows:
  build-deploy: # Limit the deployment to the master branch
    jobs:
      - build: 
          filters:
            branches:
              only: master